In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from google.colab import files

uploaded = files.upload()   # choose your .zip file from local disk

Saving thyroid+disease.zip to thyroid+disease.zip

In [ ]:
import zipfile
import os

zip_file_name = list(uploaded.keys())[0]  # gets uploaded zip filename

with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall('/content/extracted_files')

print("Files extracted to /content/extracted_files")

Files extracted to /content/extracted_files

In [ ]:
import os

os.listdir('/content/extracted_files')

['hypothyroid.data',
 'thyroid0387.data',
 'costs',
 'sick-euthyroid.data',
 'hypothyroid.names',
 'allhyper.data',
 'Index',
 'allbp.data',
 'ann-Readme',
 'allhyper.test',
 'allrep.test',
 'dis.test',
 'allhyper.names',
 'ann-test.data',
 'allrep.names',
 'sick.test',
 'thyroid0387.names',
 'allhypo.data',
 'allbp.names',
 'ann-train.data',
 'new-thyroid.data',
 'thyroid.theory',
 'allrep.data',
 'allhypo.names',
 'sick.data',
 'ann-thyroid.names',
 'HELLO',
 'dis.data',
 'allhypo.test',
 'allbp.test',
 'new-thyroid.names',
 'sick.names',
 'sick-euthyroid.names',
 'dis.names']

In [ ]:

data = pd.read_csv(
    "/content/extracted_files/thyroid0387.data",
    header=None
)

data.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,29,F,f,f,f,f,f,f,f,t,...,f,?,f,?,f,?,f,?,other,-[840801013]
1,29,F,f,f,f,f,f,f,f,f,...,t,128,f,?,f,?,f,?,other,-[840801014]
2,41,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,11,other,-[840801042]
3,36,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,26,other,-[840803046]
4,32,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,36,other,S[840803047]

In [ ]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,29,F,f,f,f,f,f,f,f,t,...,f,?,f,?,f,?,f,?,other,-[840801013]
1,29,F,f,f,f,f,f,f,f,f,...,t,128,f,?,f,?,f,?,other,-[840801014]
2,41,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,11,other,-[840801042]
3,36,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,26,other,-[840803046]
4,32,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,t,36,other,S[840803047]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9172 entries, 0 to 9171
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       9172 non-null   int64
 1   1       9172 non-null   object
 2   2       9172 non-null   object
 3   3       9172 non-null   object
 4   4       9172 non-null   object
 5   5       9172 non-null   object
 6   6       9172 non-null   object
 7   7       9172 non-null   object
 8   8       9172 non-null   object
 9   9       9172 non-null   object
 10  10      9172 non-null   object
 11  11      9172 non-null   object
 12  12      9172 non-null   object
 13  13      9172 non-null   object
 14  14      9172 non-null   object
 15  15      9172 non-null   object
 16  16      9172 non-null   object
 17  17      9172 non-null   object
 18  18      9172 non-null   object
 19  19      9172 non-null   object
 20  20      9172 non-null   object
 21  21      9172 non-null   object
 22  22      9172 non-null   object
 23  23      9172 non-null   object
 24  24      9172 non-null   object
 25  25      9172 non-null   object
 26  26      9172 non-null   object
 27  27      9172 non-null   object
 28  28      9172 non-null   object
 29  29      9172 non-null   object
dtypes: int64(1), object(29)
memory usage: 2.1+ MB

In [ ]:
data.nunique()

0      100
1        3
2        2
3        2
4        2
5        2
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       2
17     370
18       2
19      86
20       2
21     288
22       2
23     177
24       2
25     324
26       2
27      67
28       6
29    9172
dtype: int64

In [ ]:
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

In [ ]:
(data.isnull().sum()/(len(data)))*100

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
24    0.0
25    0.0
26    0.0
27    0.0
28    0.0
29    0.0
dtype: float64